### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Jahangirys** [towfiqi/serpbear#77]
![Screenshot_1](https://user-images.githubusercontent.com/124792512/217536739-5dfdbbbe-f5cd-4748-8acc-de605a4a07b2.png)
![Screenshot_5](https://user-images.githubusercontent.com/124792512/217536766-fad1cab7-e7b6-4134-b088-e0f354d570ab.png)

I found all correct. Buy not understand why showing an incorrect username.

**Comment by OrrnobMahmud** [comment]
Same here.

**Comment by towfiqi** [comment]
Are you guys running the app on windows by pulling the github repo? or trying with docker?

If you are on Mac, instead of setting `USER` env, set `USERNAME`.

**Comment by OrrnobMahmud** [comment]
Running on Windows by pulling the repo. I am not on Mac. Many says it was fine on the old version. The issue with incorrect username started with the new version.

**Comment by towfiqi** [comment]
Can you please rename the `USER` key of your env file to `USERNAME` and see if that fixes the issue for you?

**Comment by OrrnobMahmud** [comment]
![image](https://user-images.githubusercontent.com/53536803/218967819-d3eb213d-39b1-48eb-9d0a-d4b9fd19dda1.png)
Still the same.

**Comment by Jahangirys** [comment]
Still same issue.

**Comment by Jahangirys** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/124792512/218974565-6ee2c9e0-4635-435c-a9bd-bcffdb1d0533.png)
![Screenshot_10](https://user-images.githubusercontent.com/124792512/218974586-89c9cea4-2a15-4340-a5d2-41a3db478c69.png)

**Comment by towfiqi** [comment]
Ok, on investigation, looks like it is a bug. The USERNAME variable is actually reserved for windows. Will fix this in the next release. Give me a couple of hours..

**Comment by Jahangirys** [comment]
ok, bro. Thanks for your time.

**Comment by OrrnobMahmud** [comment]
> Ok, on investigation, looks like it is a bug. The USERNAME variable is actually reserved for windows. Will fix this in the next release. Give me a couple of hours..

Thanks, @towfiqi

**Comment by towfiqi** [comment]
Guys, pull the just released version and give it a try.

**Comment by OrrnobMahmud** [comment]
Its fixed now. Thanks for your effort man, really appreciate it.

**Comment by Boifuba** [comment]
This issue persist. 

V2.0.2 
Ubuntu 20.02

I tried USER and USERNAME

**Comment by pixelpaulaus** [comment]
> This issue persist.
> 
> V2.0.2 Ubuntu 20.02
> 
> I tried USER and USERNAME

same issue on Ubuntu 20.02, with a fresh install. Anyone get it working?

**Comment by Boifuba** [comment]
use this on youor next.config.js

```
/** @type {import('next').NextConfig} */
const { version } = require("./package.json");

const nextConfig = {
  reactStrictMode: true,
  swcMinify: false,
  output: "standalone",
  publicRuntimeConfig: {
    version,
  },
  env: {
    USER: "your username here",
    PASSWORD: " your password here",
  },
};

module.exports = nextConfig;
```

**Comment by Jackster** [comment]
Doing the same on Ubuntu. Used USER_NAME and it worked.
